version: '3'
services:
  leaderboard:
    build: .
    command:
      python ./project/leaderboard.py
    depends_on:
      postgres:
        condition: service_healthy
  matches:
    build: .
    command:
      python ./project/matches.py
    depends_on:
      leaderboard:
        condition: service_completed_successfully
  analyse:
    build: .
    volumes: 
      - .:/project
    command:
      python ./project/analyse.py
    depends_on:
      matches:
        condition: service_completed_successfully
  postgres:
    # Official Postgres image from DockerHub (we use the last version)
    image: 'postgres:latest'
    restart: always
    ports:
      - 5432:5432
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: postgres # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: postgres # The PostgreSQL default database (automatically created at first launch)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - 5050:80

